/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Handle returned by `listenExplorerDragFiles`.
 * Call `unregister()` to stop listening for file drags.
 */
export declare class DragHandle {
  unregister(): void
}

/**
 * Handle returned by `listen`, `listenPath` and `listenSelectedFiles`.
 * Call `unregister()` to stop listening and release the global hotkey.
 */
export declare class HotkeyHandle {
  unregister(): void
}

/** Returns the paths of the files/folders selected in the focused Explorer window. */
export declare function getExplorerSelectedFile(): Array<string>

/**
 * Returns the filesystem path of the focused Explorer window.
 *
 * Returns an error when no Explorer window is focused.
 */
export declare function getFocusedExplorerPath(): string

/** The parsed modifier flags and virtual-key code of a hotkey string. */
export interface HotkeyInfo {
  modifier: number
  key: number
}

/**
 * Registers a global hotkey and calls `callback` (with no arguments) every
 * time it is pressed.
 */
export declare function listen(hotkey: string, callback: (arg?: unknown) => unknown): HotkeyHandle

/**
 * Listens for files/folders dragged out of Explorer and calls `callback` with
 * the dragged items. Only one global listener can be active at a time.
 */
export declare function listenExplorerDragFiles(callback: (arg?: unknown) => unknown): DragHandle

/**
 * Registers a global hotkey and calls `callback` with the focused Explorer
 * path every time it is pressed.
 */
export declare function listenPath(hotkey: string, callback: (arg?: unknown) => unknown): HotkeyHandle

/**
 * Registers a global hotkey and calls `callback` with the selected
 * files/folders of the focused Explorer window every time it is pressed.
 */
export declare function listenSelectedFiles(hotkey: string, callback: (arg?: unknown) => unknown): HotkeyHandle

/**
 * Parses a hotkey string like `"Ctrl+Shift+z"` into its modifier flags and
 * virtual-key code, or `null` when the string is not a supported hotkey.
 */
export declare function parseHotkey(hotkeyStr: string): HotkeyInfo | null
